services:
  web:
    image: zoltraak-web-image
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    env_file:
      - .env
    ports:
      - "5000:5000"
    networks:
      - server_network

  db:
    image: postgres:16.0-alpine
    command: ["postgres", "-c", "log_statement=all"]
    env_file:
      - .env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - server_network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'",
        ]
      interval: 5s
      timeout: 3s
      retries: 30

  nginx:
    image: nginx:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./app/config/certificates:/etc/nginx/certificates:ro

    networks:
      - server_network

volumes:
  db-data:

networks:
  server_network:
    driver: overlay
