services:
  db:
    image: postgres:16.0-alpine
    command: ["postgres", "-c", "log_statement=all"]
    env_file:
      - .env 
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 5s
      timeout: 3s
      retries: 30
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - server_network

  web:
    build: .
    command: python3.12 run.py
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    env_file:
      - .env 
    depends_on:
      db:
        condition: service_healthy
    networks:
      - server_network

volumes:
  db-data:

networks:
  server_network:
    driver: bridge
